name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == "push"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Deploy to vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} #team_zig9QTDl5RIxGUKZTQMI9KXx
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #prj_7IcBLKlGfQtPHROI3Yy2QzkU0Rd1
          vercel-args: "--prod"